diff --git a/render.yaml b/render.yaml
new file mode 100644
index 0000000000000000000000000000000000000000..09a80f414b6f55f7c231e4b9a2edeeb37169ff59
--- /dev/null
+++ b/render.yaml
@@ -0,0 +1,13 @@
+services:
+  - type: web
+    name: suprides-app
+    env: python
+    plan: starter
+    region: frankfurt
+    buildCommand: pip install -r requirements.txt
+    startCommand: python render_start.py
+    envVars:
+      - key: PYTHON_VERSION
+        value: 3.11
+      - key: FLASK_ENV
+        value: production
